### ISSUE TITLE
strapi-provider-cloudflare-r2 @0.1.1: Name contains illegal characters

### ISSUE THREAD

**Issue by VrTech** [trieb-work/strapi-provider-cloudflare-r2#1]
[1/5] Validating package.json...
[2/5] Resolving packages...
warning strapi-provider-cloudflare-r2 > aws-sdk > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning strapi-provider-cloudflare-r2 > aws-sdk > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[3/5] Fetching packages...
error strapi-provider-cloudflare-r2 @0.1.1: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Do you have any ideas why ? 

Thanks

**Comment by JannikZed** [comment]
there is a type in the npm project name, including a trailing whitespace.. we are removing this and releasing it again soon.

**Comment by docimin** [comment]
Hey @JannikZed

When is the release coming?

**Comment by tilman** [comment]
Hey, new release is out and Issue should be solved. Please reopen if it still persists.

Sorry for waiting that long, I was on vacation :)
