### ISSUE TITLE
Cloudflare R2 integration not working with strapi

### ISSUE THREAD

**Issue by tarorg** [trieb-work/strapi-provider-cloudflare-r2#11]
I have followed all procedures as in https://market.strapi.io/providers/strapi-provider-cloudflare-r2 

but it is not working .. I have hosted strapi on digital ocean

files uploaded does not goes to R2 bucket, please help

**Comment by JannikZed** [comment]
Please provide an exact description of the problem. Did you follow all needed settings written in the README file? Are you using the environment variables starting with "CF_" not "AWS_"?

**Comment by tarorg** [comment]
I followed all needed settings in the README file
This is my repo link , I will attach environmental variables from digital ocean 

![image](https://github.com/trieb-work/strapi-provider-cloudflare-r2/assets/78031947/a92962ef-128e-4733-bb48-3c5dbe5ebfb8)

please help me with this

**Comment by JannikZed** [comment]
Please never! Publish secrets publicly. You should change your secrets now.
Please also show the error that you received.

**Comment by tarorg** [comment]
yeah I will change the secrets... there was no error shown in the log .. deployment was successful  .. 

only thing file I upload to STRAPI media does not goes to cloudflare R2
