### ISSUE TITLE
Not compatible with Node 20

### ISSUE THREAD

**Issue by sachithraSP** [trieb-work/strapi-provider-cloudflare-r2#17]
Strapi 4.19

"node": ">=18.0.0 <=20.x.x"

error strapi-provider-cloudflare-r2@0.2.4: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=19.x.x". Got "20.11.0"

**Comment by JannikZed** [comment]
@sachithraSP should be supported in the most recent release now :)
