### ISSUE TITLE
Required AWS Policy Actions?

### ISSUE THREAD

**Issue by brandondeweese-reify** [trieb-work/strapi-provider-cloudflare-r2#2]
Sorry... what does'Required AWS Policy Actions' mean and where does it get changed?

**Comment by JannikZed** [comment]
Nothing :D I think this got just copied over by mistake from the AWS S3 plugin. I removed it. Thank you for pointing that out.

**Comment by brandondeweese-reify** [comment]
It's here too. https://market.strapi.io/providers/strapi-provider-cloudflare-r2
