### ISSUE TITLE
Respect folder structure from Media Library in Cloudflare R2 file upload

### ISSUE THREAD

**Issue by MartinMikita** [trieb-work/strapi-provider-cloudflare-r2#4]
After testing your plugin I found that it does not respect the folder structure from Media Library.

Is it possible to add it?

**Comment by tilman** [comment]
For me Folder are working correctly in the Strapi Admin UI. Strapi stores the folder structure only in internal DB and not in file storage. If I'm not wrong this is the same for the official strapi upload-aws-s3 provider. 

Do I get it correctly that you wish to have the file uploaded in cloudflare r2 in the same folder as well instead plain to the root folder? This would only be possible if strapi provides the folder as an argument of the upload function [here](https://github.com/trieb-work/strapi-provider-cloudflare-r2/blob/56ea3cee8ba630e5fb1c7bf93eb3efc44f6471f8/lib/index.js#L41C21-L41C25). You can add some console logs of the file argument, maybe it includes the folder name. If so, you can add it to the file name during upload and it should work as expected. I'm happy to accept a PR if you want to add this feature 👌

**Comment by Cretezy** [comment]
Adding my 2 cents, `file` in the `upload` function includes the `folder` (set to `null` by default) and `folderPath` (set to `/` by default) properties.

I believe the Strapi media folder _should_ be included in these parameters. I think simply prefixing `Key` with `folderPath` would work (maybe also stripping leading slash).

**Comment by tilman** [comment]
I just checked file.folderPath right now. Unfortunately the folderPath is not the folder name but instead the folder ID from the DB (testFolder = ID1, testFolder2 = ID2, ...). As we do not have strapi function available in the provider we can not fetch the name from the DB. Therefore we can only upload the files to R2 into folders with the internal DB name. I have added this functionality in v.0.2.0, may it helps to organize a bit at least.

Please also notice that only new files will be uploaded to folders.

If you want to know the ID of your folder, open the media library in the admin panel. Then navigate to your folder and check the last query argument:
`http://localhost:1337/admin/plugins/upload?sort=createdAt:DESC&page=1&pageSize=10&folder=1` -> `folder=1` -> ID = **1**
