### ISSUE TITLE
console log on failure during bootstrap

### ISSUE THREAD

**Issue by regiside** [trieb-work/strapi-provider-cloudflare-r2#5]
It seems like the plugin just silently fails and falls back on the default upload when any of the provider options are not configured correctly. Would be nice if it would pass some info to the console to at least acknowledge that it tried to use the upload provider, and maybe some info about the values it tried and response it got from the endpoint.

**Comment by tilman** [comment]
Hey, I'm not able to reproduce this issue. Could you please add a strapi example repo with this problem?

**Comment by tilman** [comment]
Closed due to inactivity
