### ISSUE TITLE
Documentation recommendation: Add Endpoint Example

### ISSUE THREAD

**Issue by regiside** [trieb-work/strapi-provider-cloudflare-r2#6]
As of now there's nothing in the documentation about what your R2 Endpoint value should be or where to find it. It would be nice to add the following to the documentation on market.strapi.io/ and github:

Your cloudflare endpoint will look like: `https://<ACCOUNT_ID>.r2.cloudflarestorage.com` 

To find your account ID:
1. Log in to the Cloudflare dashboard and select your account and domain.
2. On the Overview page (the landing page for your domain), find the API section.

![dash-overview-api-highlighted_hu9300eadd9165939b8fbde60fd27c88b1_508954_2357x3172_resize_q75_box_3-6cb261fd](https://github.com/trieb-work/strapi-provider-cloudflare-r2/assets/10213359/def6d905-eaf9-456a-b285-60ed5a594e21)

**Comment by JannikZed** [comment]
Done!
