### ISSUE TITLE
Provider conflicts with aws-r3 upload provider.

### ISSUE THREAD

**Issue by regiside** [trieb-work/strapi-provider-cloudflare-r2#7]
I have variables in my .env file left over from when I was using the aws-r3 upload provider. These AWS named variables are still being pulled in and trying to be used by the r2 plugin even though I don't pass them anywhere in the configuration. I'm specifically seeing this with the "AWS_REGION" variable.  Code probably needs to be cleaned up to make sure the plugins can exist on the same strapi server without conflicting. 

<img width="352" alt="Screen Shot 2023-06-30 at 11 17 26 AM" src="https://github.com/trieb-work/strapi-provider-cloudflare-r2/assets/10213359/ee301494-b262-4199-8523-6f6db136fbfd">

**My .env file:**

CF_PUBLIC_ACCESS_URL = "r2.findmymission.com"
CF_ACCESS_KEY_ID = "..."
CF_ACCESS_SECRET = "..."
CF_ENDPOINT = "..."
CF_BUCKET = "findmymission"

CDN_URL=""
CDN_ROOT_PATH="/"
AWS_ACCESS_KEY_ID="..."
AWS_ACCESS_SECRET="..."
AWS_REGION="us-east-2"
AWS_ACL=""
AWS_SIGNED_URL_EXPIRES=""
AWS_BUCKET="findmymission"

**My plugins.js file:**
module.exports = ({ env }) => ({

  upload: {
    config: {
      provider: "strapi-provider-cloudflare-r2",
      providerOptions: {
        accessKeyId: env("CF_ACCESS_KEY_ID"),
        secretAccessKey: env("CF_ACCESS_SECRET"),
        endpoint: env("CF_ENDPOINT"),
        params: {
          Bucket: env("CF_BUCKET"),
        },
        cloudflarePublicAccessUrl: env("CF_PUBLIC_ACCESS_URL"),
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
  // ...
});

**Comment by tilman** [comment]
Hey @regiside thanks for spotting this issue. The Plugin itself does not have any usage of `AWS_` env variables. But we use `aws-sdk` package as a dependency wich get's configured via the `AWS_` env variables. I have added an Info to the Readme that it is recommended to delete these unused env variables. Do you think this is enough?

If not, you can also open a PR and add some functionality [in this line](https://github.com/trieb-work/strapi-provider-cloudflare-r2/blob/56ea3cee8ba630e5fb1c7bf93eb3efc44f6471f8/lib/index.js#L35) to check if any `AWS_...` env var is set.

**Comment by tilman** [comment]
I have added a check to plugin bootstrap as well. Check out version v0.2.1
